# Generated by Django 5.1.3 on 2024-12-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='juXgJB', max_length=6, unique=True),
        ),
    ]
