# Generated by Django 5.1.3 on 2024-12-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_user_invite_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_phone_n_a3b1c5_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='8Snspw', editable=False, max_length=6, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number', 'invite_code'], name='users_phone_n_88119f_idx'),
        ),
    ]
